M48
; DRILL file {KiCad 9.0.6} date 2026-02-13T20:59:40+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-13T20:59:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X191.727Y-92.218
X191.727Y-97.998
T2
X102.477Y-126.708
M30
